Loading rhel8/default-amp
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 libpciaccess/0.16/gcc-9.4.0-6fonbj6
    libiconv/1.16/gcc-9.4.0-ahebbov libxml2/2.9.12/gcc-9.4.0-gnknt5e
    ncurses/6.2/gcc-9.4.0-aiirok7 hwloc/2.5.0/gcc-9.4.0-7sqomga
    libevent/2.1.12/gcc-9.4.0-hgny7cm numactl/2.0.14/gcc-9.4.0-52dwc6n
    cuda/11.4.0/gcc-9.4.0-3hnxhjt gdrcopy/2.2/gcc-9.4.0-e4igtfp
    knem/1.1.4/gcc-9.4.0-bpbxgva libnl/3.3.0/gcc-9.4.0-whwhrwb
    rdma-core/34.0/gcc-9.4.0-5eo5n2u ucx/1.11.1/gcc-9.4.0-lktqyl4
    openmpi/4.1.1/gcc-9.4.0-epagguv
Changed directory to /rds/user/rfsm2/hpc-work/edm2_hig.

JobID: 61890986
======
Time: Sun Sep 29 13:47:08 BST 2024
Running on master node: gpu-q-59
Current directory: /rds/user/rfsm2/hpc-work/edm2_hig

Nodes allocated:
================
gpu-q-59

numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
torchrun --nproc_per_node=4 --standalone /rds/user/rfsm2/hpc-work/edm2_hig/train_edm2_hignn.py --outdir=/home/rfsm2/rds/hpc-work/training_runs --preset=edm2-img512-m --batch-gpu=512 --cond=True --path=/home/rfsm2/rds/hpc-work/datasets/coco/coco_train2017_hig.h5 --val_path=/home/rfsm2/rds/hpc-work/datasets/coco/coco_val2017_hig.h5  > logs/out.61890986.log

/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3486], which does not match the required output shape [3486, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3489], which does not match the required output shape [3489, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3523], which does not match the required output shape [3523, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3392], which does not match the required output shape [3392, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3373], which does not match the required output shape [3373, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3444], which does not match the required output shape [3444, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3485], which does not match the required output shape [3485, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3855], which does not match the required output shape [3855, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3436], which does not match the required output shape [3436, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3490], which does not match the required output shape [3490, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3552], which does not match the required output shape [3552, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch_geometric/data/collate.py:204: UserWarning: An output with one or more elements was resized since it had shape [3504], which does not match the required output shape [3504, 768]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
W0929 18:15:48.591000 140037976333312 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 801082 closing signal SIGTERM
W0929 18:15:48.592000 140037976333312 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 801083 closing signal SIGTERM
W0929 18:15:48.592000 140037976333312 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 801084 closing signal SIGTERM
/home/rfsm2/.conda/envs/edm2/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 40 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
E0929 18:15:50.959000 140037976333312 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 3 (pid: 801085) of binary: /home/rfsm2/.conda/envs/edm2/bin/python
Traceback (most recent call last):
  File "/home/rfsm2/.conda/envs/edm2/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rfsm2/.conda/envs/edm2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/rds/user/rfsm2/hpc-work/edm2_hig/train_edm2_hignn.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-29_18:15:48
  host      : gpu-q-59.data.cluster
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 801085)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
